/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 使用邮箱和密码注册 */
    post: operations['registerWithEmail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 使用邮箱和密码登录 */
    post: operations['loginWithPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/qq/authorize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 开始 QQ OAuth 登录 */
    get: operations['authorizeQq'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/qq/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 处理 QQ OAuth 回调 */
    get: operations['handleQqCallback'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 使用 HttpOnly Cookie 刷新访问令牌 */
    post: operations['refreshAccessToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 注销当前会话 */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password/forgot': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 请求密码重置 */
    post: operations['requestPasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 使用一次性令牌重置密码 */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/password/change': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 修改当前用户密码并轮换会话 */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/auth/check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 校验管理端访问权限 */
    get: operations['checkAdminAccess'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取当前用户 */
    get: operations['getCurrentUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 更新当前用户资料 */
    patch: operations['updateCurrentUser'];
    trace?: never;
  };
  '/ledgers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取可访问账本 */
    get: operations['listLedgers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ledgers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    /** 获取账本详情 */
    get: operations['getLedger'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/couple-ledgers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建情侣账本 */
    post: operations['createCoupleLedger'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/couple-ledgers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 解散情侣账本 */
    delete: operations['dissolveCoupleLedger'];
    options?: never;
    head?: never;
    /** 更新情侣账本 */
    patch: operations['updateCoupleLedger'];
    trace?: never;
  };
  '/couple-ledgers/{id}/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 创建有时效的情侣邀请 */
    post: operations['createCoupleInvitation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/couple-invitations/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 接受情侣邀请 */
    post: operations['acceptCoupleInvitation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/couple-ledgers/{id}/leave': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 普通成员退出情侣账本 */
    post: operations['leaveCoupleLedger'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/couple-ledgers/{id}/transfer-ownership': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 将所有权转移给另一名有效成员 */
    post: operations['transferCoupleLedgerOwnership'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取当前成员可见的账本分类与服务端权限能力 */
    get: operations['listCategories'];
    put?: never;
    /** 在账本中幂等创建自定义分类 */
    post: operations['createCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** OWNER 按账本和收支类型重排全部分类 */
    put: operations['reorderCategories'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 更新个人分类 */
    patch: operations['updateCategory'];
    trace?: never;
  };
  '/categories/{id}/enable': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 重新启用分类 */
    post: operations['enableCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories/{id}/disable': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 停用分类并保留历史引用 */
    post: operations['disableCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/entries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 分页查询账目
     * @description month 缺省时使用当前用户时区的当前月份；仅返回未软删除账目。
     */
    get: operations['listEntries'];
    put?: never;
    /**
     * 创建手工账目
     * @description 相同用户和操作下使用不可变创建请求哈希判断重放；不同载荷、legacy 记录或已删除原记录返回 409。
     */
    post: operations['createEntry'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/entries/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    /** 获取账目详情 */
    get: operations['getEntry'];
    put?: never;
    post?: never;
    /**
     * 软删除账目
     * @description 重试仍会重新校验账本可见性、操作者权限、来源类型和版本。
     */
    delete: operations['deleteEntry'];
    options?: never;
    head?: never;
    /** 更新手工账目 */
    patch: operations['updateEntry'];
    trace?: never;
  };
  '/debts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询本人借贷 */
    get: operations['listDebts'];
    put?: never;
    /** 创建本人借贷 */
    post: operations['createDebt'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/debts/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    /** 获取本人借贷详情 */
    get: operations['getDebt'];
    put?: never;
    post?: never;
    /** 软删除本人借贷 */
    delete: operations['deleteDebt'];
    options?: never;
    head?: never;
    /** 更新本人借贷 */
    patch: operations['updateDebt'];
    trace?: never;
  };
  '/debts/{id}/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 记录还款或收款 */
    post: operations['createDebtTransaction'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/recurring-rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询可见周期规则 */
    get: operations['listRecurringRules'];
    put?: never;
    /** 创建周期规则 */
    post: operations['createRecurringRule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/recurring-rules/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    /** 获取周期规则详情 */
    get: operations['getRecurringRule'];
    put?: never;
    post?: never;
    /** 结束并软删除周期规则 */
    delete: operations['deleteRecurringRule'];
    options?: never;
    head?: never;
    /** 更新周期规则 */
    patch: operations['updateRecurringRule'];
    trace?: never;
  };
  '/recurring-rules/{id}/pause': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 暂停周期规则 */
    post: operations['pauseRecurringRule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/recurring-rules/{id}/resume': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 恢复周期规则 */
    post: operations['resumeRecurringRule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/recurring-runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询可见周期实例 */
    get: operations['listRecurringRuns'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/recurring-runs/{id}/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 确认周期实例并入账 */
    post: operations['confirmRecurringRun'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/recurring-runs/{id}/skip': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 跳过待确认周期实例 */
    post: operations['skipRecurringRun'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/salary/profiles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询本人工资档案 */
    get: operations['listSalaryProfiles'];
    put?: never;
    /** 创建本人工资档案 */
    post: operations['createSalaryProfile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/salary/profiles/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 更新本人工资档案 */
    patch: operations['updateSalaryProfile'];
    trace?: never;
  };
  '/salary/records': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询本人工资记录 */
    get: operations['listSalaryRecords'];
    put?: never;
    /** 创建本人工资记录 */
    post: operations['createSalaryRecord'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/salary/records/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    /** 获取本人工资记录详情 */
    get: operations['getSalaryRecord'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** 更新未到账工资记录 */
    patch: operations['updateSalaryRecord'];
    trace?: never;
  };
  '/salary/records/{id}/mark-paid': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 确认工资到账 */
    post: operations['markSalaryPaid'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/salary/summary/{year}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        year: components['parameters']['Year'];
      };
      cookie?: never;
    };
    /** 获取本人年度工资汇总 */
    get: operations['getSalarySummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/salary/balance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取本人工资周期余额 */
    get: operations['getSalaryBalance'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/saving-goals': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询可见攒钱目标 */
    get: operations['listSavingGoals'];
    put?: never;
    /** 创建攒钱目标 */
    post: operations['createSavingGoal'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/saving-goals/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    /** 获取攒钱目标详情 */
    get: operations['getSavingGoal'];
    put?: never;
    post?: never;
    /** 软删除攒钱目标 */
    delete: operations['deleteSavingGoal'];
    options?: never;
    head?: never;
    /** 更新攒钱目标 */
    patch: operations['updateSavingGoal'];
    trace?: never;
  };
  '/saving-goals/{id}/contributions': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 添加本人存入记录 */
    post: operations['addSavingContribution'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/saving-goals/{goalId}/contributions/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goalId: components['parameters']['GoalId'];
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** 软删除本人存入记录 */
    delete: operations['deleteSavingContribution'];
    options?: never;
    head?: never;
    /** 更新本人存入记录 */
    patch: operations['updateSavingContribution'];
    trace?: never;
  };
  '/statistics/overview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取账本统计概览 */
    get: operations['getStatisticsOverview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/statistics/trend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取账本收支趋势 */
    get: operations['getStatisticsTrend'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/statistics/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取账本分类统计 */
    get: operations['getStatisticsCategories'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/statistics/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取情侣成员对比 */
    get: operations['getStatisticsMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 查询本人站内通知 */
    get: operations['listNotifications'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 标记本人通知已读 */
    post: operations['markNotificationsRead'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/exports/entries.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 导出可访问账目 CSV */
    get: operations['exportEntriesCsv'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/exports/salary.csv': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 导出本人工资 CSV */
    get: operations['exportSalaryCsv'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Format: int64
     * @description 整数分，不得超过 JavaScript 安全整数。
     */
    Cent: number;
    /** Format: int64 */
    NonNegativeCent: number;
    /**
     * Format: int64
     * @description 可为负数的整数分，不得超出 JavaScript 安全整数。
     */
    SignedCent: number;
    /** Format: date */
    BusinessDate: string;
    /**
     * Format: date-time
     * @description UTC ISO 8601 时间。
     */
    Timestamp: string;
    IdempotencyKey: string;
    /** @enum {string} */
    EntryType: 'INCOME' | 'EXPENSE';
    /** @enum {string} */
    EntrySourceType: 'MANUAL' | 'SALARY' | 'DEBT_TRANSACTION' | 'RECURRING_RUN';
    /** @enum {string} */
    EntryPaymentMethod: 'CASH' | 'WECHAT' | 'ALIPAY' | 'BANK_CARD' | 'OTHER';
    /** @enum {string} */
    CategoryIconKey:
      | 'food'
      | 'shopping'
      | 'transport'
      | 'housing'
      | 'entertainment'
      | 'medical'
      | 'education'
      | 'gift'
      | 'salary'
      | 'bonus'
      | 'part_time'
      | 'investment'
      | 'red_packet'
      | 'refund'
      | 'other';
    CategoryColor: string;
    /** @enum {string} */
    RecurringRunStatus: 'PENDING' | 'GENERATED' | 'CONFIRMED' | 'SKIPPED' | 'FAILED';
    User: {
      /** Format: uuid */
      id: string;
      nickname: string;
      /** Format: uri */
      avatarUrl?: string | null;
      timezone: string;
      /** @enum {string} */
      status: 'ACTIVE' | 'DISABLED';
      /** Format: email */
      email: string | null;
      roles: ('USER' | 'ADMIN')[];
      permissions: string[];
    };
    Ledger: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      type: 'PERSONAL' | 'COUPLE';
      name: string;
      /** Format: uuid */
      ownerUserId: string;
      /** @enum {string} */
      status: 'ACTIVE' | 'DISSOLVED';
      members: components['schemas']['LedgerMember'][];
    };
    LedgerMember: {
      /** Format: uuid */
      userId: string;
      /** @enum {string} */
      role: 'OWNER' | 'MEMBER';
      joinedAt: components['schemas']['Timestamp'];
      nickname: string;
      /** Format: uri */
      avatarUrl?: string | null;
    };
    CoupleInvitation: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      ledgerId: string;
      /** @enum {string} */
      status: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED';
      expiresAt: components['schemas']['Timestamp'];
    };
    Category: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      ledgerId: string;
      /** Format: uuid */
      creatorUserId: string | null;
      type: components['schemas']['EntryType'];
      name: string;
      icon: components['schemas']['CategoryIconKey'];
      color: components['schemas']['CategoryColor'];
      sortOrder: number;
      isSystem: boolean;
      isEnabled: boolean;
      canEdit: boolean;
      canToggle: boolean;
      createdAt: components['schemas']['Timestamp'];
      updatedAt: components['schemas']['Timestamp'];
    };
    Entry: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      ledgerId: string;
      type: components['schemas']['EntryType'];
      amountCent: components['schemas']['Cent'];
      businessDate: components['schemas']['BusinessDate'];
      note: string | null;
      paymentMethod: components['schemas']['EntryPaymentMethod'] | null;
      sourceType: components['schemas']['EntrySourceType'];
      creator: components['schemas']['EntryCreator'];
      category: components['schemas']['EntryCategorySummary'];
      createdAt: components['schemas']['Timestamp'];
      updatedAt: components['schemas']['Timestamp'];
      version: number;
      canEdit: boolean;
      canDelete: boolean;
    };
    EntryCreator: {
      /** Format: uuid */
      id: string;
      nickname: string;
      /** Format: uri */
      avatarUrl: string | null;
    };
    EntryCategorySummary: {
      /** Format: uuid */
      id: string;
      name: string;
      icon: components['schemas']['CategoryIconKey'];
      color: components['schemas']['CategoryColor'];
      isEnabled: boolean;
    };
    Debt: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      direction: 'BORROWED' | 'LENT';
      counterpartyName: string;
      principalCent: components['schemas']['Cent'];
      processedCent: components['schemas']['NonNegativeCent'];
      remainingCent: components['schemas']['NonNegativeCent'];
      startDate: components['schemas']['BusinessDate'];
      dueDate: components['schemas']['BusinessDate'] | null;
      /** @enum {string} */
      status: 'ACTIVE' | 'SETTLED' | 'OVERDUE' | 'CANCELLED';
      overdueDays: number;
      note: string | null;
      reminderEnabled: boolean;
      readonly canEdit: boolean;
      readonly canDelete: boolean;
      /** Format: date-time */
      readonly createdAt: string;
      /** Format: date-time */
      readonly updatedAt: string;
      transactions?: components['schemas']['DebtTransaction'][];
    };
    DebtTransaction: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      debtId: string;
      /** Format: uuid */
      userId: string;
      amountCent: components['schemas']['Cent'];
      businessDate: components['schemas']['BusinessDate'];
      syncEntry: boolean;
      /** Format: uuid */
      entryId: string | null;
      note: string | null;
      /** Format: date-time */
      readonly createdAt: string;
    };
    RecurringRule: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      ownerUserId: string;
      /** Format: uuid */
      ledgerId: string;
      name: string;
      entryType: components['schemas']['EntryType'];
      amountCent: components['schemas']['Cent'];
      /** Format: uuid */
      categoryId: string;
      category: components['schemas']['EntryCategorySummary'];
      /** @enum {string} */
      frequency: 'MONTHLY' | 'YEARLY';
      intervalValue: number;
      startDate: components['schemas']['BusinessDate'];
      endDate: components['schemas']['BusinessDate'] | null;
      totalOccurrences: number | null;
      completedOccurrences: number;
      nextRunDate: components['schemas']['BusinessDate'] | null;
      /** @enum {string} */
      generationMode: 'AUTO' | 'CONFIRM';
      /** @enum {string} */
      status: 'ACTIVE' | 'PAUSED' | 'COMPLETED' | 'CANCELLED';
      reminderDaysBefore: number;
      readonly canEdit: boolean;
      readonly canPause: boolean;
      readonly canResume: boolean;
      readonly canDelete: boolean;
      createdAt: components['schemas']['Timestamp'];
      updatedAt: components['schemas']['Timestamp'];
    };
    RecurringRuleSummary: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      ledgerId: string;
      /** Format: uuid */
      ownerUserId: string;
      name: string;
      entryType: components['schemas']['EntryType'];
      /** @enum {string} */
      generationMode: 'AUTO' | 'CONFIRM';
    };
    RecurringRun: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      ruleId: string;
      scheduledDate: components['schemas']['BusinessDate'];
      amountCent: components['schemas']['Cent'];
      status: components['schemas']['RecurringRunStatus'];
      /** Format: uuid */
      entryId: string | null;
      attempts: number;
      lastError: string | null;
      lastAttemptAt: components['schemas']['Timestamp'] | null;
      confirmedAt: components['schemas']['Timestamp'] | null;
      readonly canConfirm: boolean;
      readonly canSkip: boolean;
      rule: components['schemas']['RecurringRuleSummary'];
      createdAt: components['schemas']['Timestamp'];
      updatedAt: components['schemas']['Timestamp'];
    };
    SalaryProfile: {
      /** Format: uuid */
      id: string;
      name: string;
      employerName: string | null;
      payDay: number;
      defaultSyncEntry: boolean;
      /** @enum {string} */
      status: 'ACTIVE' | 'INACTIVE';
      defaultItems: components['schemas']['SalaryProfileItem'][];
      readonly canEdit: boolean;
      createdAt: components['schemas']['Timestamp'];
      updatedAt: components['schemas']['Timestamp'];
    };
    SalaryProfileItem: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      itemType: 'EARNING' | 'DEDUCTION';
      itemCode: string;
      itemName: string;
      amountCent: components['schemas']['NonNegativeCent'];
      sortOrder: number;
    };
    SalaryProfileSummary: {
      /** Format: uuid */
      id: string;
      name: string;
      employerName: string | null;
      payDay: number;
    };
    SalaryRecord: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      profileId: string;
      profile: components['schemas']['SalaryProfileSummary'];
      salaryMonth: components['schemas']['BusinessDate'];
      grossCent: components['schemas']['NonNegativeCent'];
      deductionCent: components['schemas']['NonNegativeCent'];
      netCent: components['schemas']['NonNegativeCent'];
      /** @enum {string} */
      paymentStatus: 'UNPAID' | 'PAID';
      paidDate: components['schemas']['BusinessDate'] | null;
      /** Format: uuid */
      entryId: string | null;
      items: components['schemas']['SalaryItem'][];
      readonly canEdit: boolean;
      createdAt: components['schemas']['Timestamp'];
      updatedAt: components['schemas']['Timestamp'];
    };
    SalaryItem: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      itemType: 'EARNING' | 'DEDUCTION';
      itemCode: string;
      itemName: string;
      amountCent: components['schemas']['Cent'];
      sortOrder: number;
    };
    SalaryMonthlySummary: {
      month: string;
      grossCent: components['schemas']['NonNegativeCent'];
      deductionCent: components['schemas']['NonNegativeCent'];
      netCent: components['schemas']['NonNegativeCent'];
      bonusCent: components['schemas']['NonNegativeCent'];
      pensionInsuranceCent: components['schemas']['NonNegativeCent'];
      medicalInsuranceCent: components['schemas']['NonNegativeCent'];
      unemploymentInsuranceCent: components['schemas']['NonNegativeCent'];
      housingProvidentFundCent: components['schemas']['NonNegativeCent'];
      incomeTaxCent: components['schemas']['NonNegativeCent'];
    };
    SalaryAnnualSummary: {
      year: number;
      recordCount: number;
      recordedMonthCount: number;
      grossCent: components['schemas']['NonNegativeCent'];
      deductionCent: components['schemas']['NonNegativeCent'];
      netCent: components['schemas']['NonNegativeCent'];
      averageMonthlyNetCent: components['schemas']['NonNegativeCent'];
      bonusCent: components['schemas']['NonNegativeCent'];
      pensionInsuranceCent: components['schemas']['NonNegativeCent'];
      medicalInsuranceCent: components['schemas']['NonNegativeCent'];
      unemploymentInsuranceCent: components['schemas']['NonNegativeCent'];
      housingProvidentFundCent: components['schemas']['NonNegativeCent'];
      incomeTaxCent: components['schemas']['NonNegativeCent'];
      items: components['schemas']['SalaryMonthlySummary'][];
      /**
       * @description 客户端必须提示专项数据来自用户工资记录，不代表官方账户余额。
       * @constant
       */
      officialBalanceDisclaimer: true;
    };
    SalaryAnnualSummaryResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['SalaryAnnualSummary'];
      requestId: string;
    };
    SalaryBalance: {
      available: boolean;
      asOfDate: components['schemas']['BusinessDate'];
      salaryRecordId: string | null;
      profileId: string | null;
      salaryMonth: components['schemas']['BusinessDate'] | null;
      paidDate: components['schemas']['BusinessDate'] | null;
      nextExpectedPayDate: components['schemas']['BusinessDate'] | null;
      periodStartDate: components['schemas']['BusinessDate'] | null;
      periodEndDate: components['schemas']['BusinessDate'] | null;
      netSalaryCent: components['schemas']['NonNegativeCent'];
      fixedExpenseCent: components['schemas']['NonNegativeCent'];
      dailyExpenseCent: components['schemas']['NonNegativeCent'];
      totalExpenseCent: components['schemas']['NonNegativeCent'];
      remainingCent: components['schemas']['SignedCent'];
      remainingDays: number;
      dailyAvailableCent: components['schemas']['SignedCent'] | null;
    };
    SalaryBalanceResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['SalaryBalance'];
      requestId: string;
    };
    SavingContributorSummary: {
      /** Format: uuid */
      userId: string;
      contributorName: string;
      amountCent: components['schemas']['NonNegativeCent'];
    };
    SavingGoal: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      ledgerId: string;
      ledgerName: string;
      /** @enum {string} */
      ledgerType: 'PERSONAL' | 'COUPLE';
      /** Format: uuid */
      creatorUserId: string;
      creatorName: string;
      name: string;
      targetCent: components['schemas']['Cent'];
      initialCent: components['schemas']['NonNegativeCent'];
      savedCent: components['schemas']['NonNegativeCent'];
      remainingCent: components['schemas']['NonNegativeCent'];
      progressBasisPoints: number;
      targetDate: components['schemas']['BusinessDate'] | null;
      /** @enum {string} */
      status: 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
      /** Format: uri */
      coverUrl: string | null;
      note: string | null;
      contributorSummaries: components['schemas']['SavingContributorSummary'][];
      readonly canManage: boolean;
      readonly canContribute: boolean;
      createdAt: components['schemas']['Timestamp'];
      updatedAt: components['schemas']['Timestamp'];
    };
    SavingGoalDetail: components['schemas']['SavingGoal'] & {
      contributions: components['schemas']['SavingContribution'][];
    };
    SavingContribution: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      goalId: string;
      /** Format: uuid */
      userId: string;
      contributorName: string;
      amountCent: components['schemas']['Cent'];
      businessDate: components['schemas']['BusinessDate'];
      note: string | null;
      readonly canEdit: boolean;
      readonly canDelete: boolean;
      createdAt: components['schemas']['Timestamp'];
      updatedAt: components['schemas']['Timestamp'];
    };
    Notification: {
      /** Format: uuid */
      id: string;
      type: string;
      title: string;
      content: string;
      readAt?: components['schemas']['Timestamp'] | null;
      createdAt: components['schemas']['Timestamp'];
    };
    DomainResource:
      | components['schemas']['User']
      | components['schemas']['Ledger']
      | components['schemas']['Category']
      | components['schemas']['Entry']
      | components['schemas']['Debt']
      | components['schemas']['DebtTransaction']
      | components['schemas']['RecurringRule']
      | components['schemas']['RecurringRun']
      | components['schemas']['SalaryProfile']
      | components['schemas']['SalaryRecord']
      | components['schemas']['SavingGoal']
      | components['schemas']['SavingContribution']
      | components['schemas']['Notification'];
    ResourceResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['DomainResource'];
      requestId: string;
    };
    SalaryProfileResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['SalaryProfile'];
      requestId: string;
    };
    SalaryProfileListResponse: {
      /** @constant */
      success: true;
      data: {
        items: components['schemas']['SalaryProfile'][];
      };
      requestId: string;
    };
    SalaryRecordResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['SalaryRecord'];
      requestId: string;
    };
    SalaryRecordListResponse: {
      /** @constant */
      success: true;
      data: {
        items: components['schemas']['SalaryRecord'][];
        page: number;
        pageSize: number;
        total: number;
        hasNext: boolean;
      };
      requestId: string;
    };
    EntryResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['Entry'];
      requestId: string;
    };
    EntryListResponse: {
      /** @constant */
      success: true;
      data: {
        items: components['schemas']['Entry'][];
        page: number;
        pageSize: number;
        total: number;
        hasNext: boolean;
      };
      requestId: string;
    };
    EntryDeleteResponse: {
      /** @constant */
      success: true;
      data: {
        /** Format: uuid */
        id: string;
        /** @constant */
        deleted: true;
        version: number;
      };
      requestId: string;
    };
    InvitationCreatedResponse: {
      /** @constant */
      success: true;
      data: {
        invitation: components['schemas']['CoupleInvitation'];
        token: string;
      };
      requestId: string;
    };
    ResourceListResponse: {
      /** @constant */
      success: true;
      data: {
        items: components['schemas']['DomainResource'][];
        page: number;
        pageSize: number;
        total: number;
        hasNext: boolean;
      };
      requestId: string;
    };
    SavingGoalResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['SavingGoal'];
      requestId: string;
    };
    SavingGoalDetailResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['SavingGoalDetail'];
      requestId: string;
    };
    SavingGoalListResponse: {
      /** @constant */
      success: true;
      data: {
        items: components['schemas']['SavingGoal'][];
        page: number;
        pageSize: number;
        total: number;
        hasNext: boolean;
      };
      requestId: string;
    };
    SavingContributionResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['SavingContribution'];
      requestId: string;
    };
    SavingDeleteResponse: {
      /** @constant */
      success: true;
      data: {
        /** Format: uuid */
        id: string;
        /** @constant */
        deleted: true;
      };
      requestId: string;
    };
    CategoryListResponse: {
      /** @constant */
      success: true;
      data: {
        items: components['schemas']['Category'][];
        permissions: {
          canCreate: boolean;
          canReorder: boolean;
        };
      };
      requestId: string;
    };
    ActionResponse: {
      /** @constant */
      success: true;
      data: {
        status: string;
      };
      requestId: string;
    };
    StatisticsOverviewResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['StatisticsOverview'];
      requestId: string;
    };
    StatisticsOverview: {
      /** Format: uuid */
      ledgerId: string;
      /** @enum {string} */
      ledgerType: 'PERSONAL' | 'COUPLE';
      month: string;
      incomeCent: number;
      expenseCent: number;
      balanceCent: number;
      averageDailyExpenseCent: number;
      largestExpenseCent: number;
      entryCount: number;
    };
    StatisticsTrendResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['StatisticsTrend'];
      requestId: string;
    };
    StatisticsTrend: {
      /** Format: uuid */
      ledgerId: string;
      /** @enum {string} */
      ledgerType: 'PERSONAL' | 'COUPLE';
      month: string;
      items: {
        /** Format: date */
        date: string;
        incomeCent: number;
        expenseCent: number;
      }[];
    };
    StatisticsCategoriesResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['StatisticsCategories'];
      requestId: string;
    };
    StatisticsCategories: {
      /** Format: uuid */
      ledgerId: string;
      /** @enum {string} */
      ledgerType: 'PERSONAL' | 'COUPLE';
      month: string;
      /** @constant */
      type: 'EXPENSE';
      totalCent: number;
      items: {
        /** Format: uuid */
        categoryId: string;
        name: string;
        icon: string;
        color: string;
        isEnabled: boolean;
        amountCent: number;
        basisPoints: number;
        entryCount: number;
      }[];
    };
    StatisticsMembersResponse: {
      /** @constant */
      success: true;
      data: components['schemas']['StatisticsMembers'];
      requestId: string;
    };
    StatisticsMembers: {
      /** Format: uuid */
      ledgerId: string;
      /** @enum {string} */
      ledgerType: 'PERSONAL' | 'COUPLE';
      month: string;
      totalCent: number;
      items: {
        /** Format: uuid */
        userId: string;
        nickname: string;
        /** Format: uri */
        avatarUrl: string | null;
        /** @enum {string} */
        memberStatus: 'ACTIVE' | 'LEFT';
        isCurrentUser: boolean;
        amountCent: number;
        basisPoints: number;
        entryCount: number;
      }[];
    };
    ErrorResponse: {
      /** @constant */
      success: false;
      code: string;
      message: string;
      details: {
        [key: string]: unknown;
      };
      requestId: string;
    };
    AuthTokenResponse: {
      /** @constant */
      success: true;
      data: {
        accessToken: string;
        /** @constant */
        expiresIn: 900;
        user: components['schemas']['User'];
      };
      requestId: string;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
      nickname: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    ForgotPasswordRequest: {
      /** Format: email */
      email: string;
    };
    ResetPasswordRequest: {
      token: string;
      newPassword: string;
    };
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    UpdateUserRequest: {
      nickname?: string;
      /** Format: uri */
      avatarUrl?: string | null;
      timezone?: string;
    };
    CreateCoupleLedgerRequest: {
      /** @default 朝暮同笺 */
      name: string;
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    UpdateCoupleLedgerRequest: {
      name: string;
    };
    AcceptInvitationRequest: {
      token: string;
    };
    CreateCoupleInvitationRequest: {
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    TransferCoupleOwnershipRequest: {
      /** Format: uuid */
      targetUserId: string;
    };
    CreateCategoryRequest: {
      /** Format: uuid */
      ledgerId: string;
      type: components['schemas']['EntryType'];
      name: string;
      icon: components['schemas']['CategoryIconKey'];
      color: components['schemas']['CategoryColor'];
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    UpdateCategoryRequest: {
      name?: string;
      icon?: components['schemas']['CategoryIconKey'];
      color?: components['schemas']['CategoryColor'];
    };
    ReorderCategoriesRequest: {
      /** Format: uuid */
      ledgerId: string;
      type: components['schemas']['EntryType'];
      categoryIds: string[];
    };
    CreateEntryRequest: {
      /** Format: uuid */
      ledgerId: string;
      type: components['schemas']['EntryType'];
      amountCent: components['schemas']['Cent'];
      /** Format: uuid */
      categoryId: string;
      businessDate: components['schemas']['BusinessDate'];
      note?: string | null;
      paymentMethod?: components['schemas']['EntryPaymentMethod'] | null;
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    UpdateEntryRequest: {
      expectedVersion: number;
      type?: components['schemas']['EntryType'];
      amountCent?: components['schemas']['Cent'];
      /** Format: uuid */
      categoryId?: string;
      businessDate?: components['schemas']['BusinessDate'];
      note?: string | null;
      paymentMethod?: components['schemas']['EntryPaymentMethod'] | null;
    };
    CreateDebtRequest: {
      /** @enum {string} */
      direction: 'BORROWED' | 'LENT';
      counterpartyName: string;
      principalCent: components['schemas']['Cent'];
      startDate: components['schemas']['BusinessDate'];
      dueDate?: components['schemas']['BusinessDate'] | null;
      note?: string | null;
      /** @default false */
      reminderEnabled: boolean;
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    UpdateDebtRequest: {
      counterpartyName?: string;
      dueDate?: components['schemas']['BusinessDate'] | null;
      note?: string | null;
      reminderEnabled?: boolean;
    };
    CreateDebtTransactionRequest: {
      amountCent: components['schemas']['Cent'];
      businessDate: components['schemas']['BusinessDate'];
      syncEntry: boolean;
      idempotencyKey: components['schemas']['IdempotencyKey'];
      note?: string | null;
    };
    CreateRecurringRuleRequest: {
      /** Format: uuid */
      ledgerId: string;
      name: string;
      entryType: components['schemas']['EntryType'];
      amountCent: components['schemas']['Cent'];
      /** Format: uuid */
      categoryId: string;
      /** @enum {string} */
      frequency: 'MONTHLY' | 'YEARLY';
      /** @default 1 */
      intervalValue: number;
      startDate: components['schemas']['BusinessDate'];
      endDate?: components['schemas']['BusinessDate'] | null;
      totalOccurrences?: number | null;
      /** @enum {string} */
      generationMode: 'AUTO' | 'CONFIRM';
      /** @default 1 */
      reminderDaysBefore: number;
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    UpdateRecurringRuleRequest: {
      name?: string;
      entryType?: components['schemas']['EntryType'];
      amountCent?: components['schemas']['Cent'];
      /** Format: uuid */
      categoryId?: string;
      /** @enum {string} */
      frequency?: 'MONTHLY' | 'YEARLY';
      intervalValue?: number;
      startDate?: components['schemas']['BusinessDate'];
      endDate?: components['schemas']['BusinessDate'] | null;
      totalOccurrences?: number | null;
      /** @enum {string} */
      generationMode?: 'AUTO' | 'CONFIRM';
      reminderDaysBefore?: number;
    };
    ConfirmRecurringRunRequest: {
      amountCent: components['schemas']['Cent'];
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    CreateSalaryProfileRequest: {
      name: string;
      employerName?: string | null;
      payDay: number;
      defaultSyncEntry: boolean;
      defaultItems: components['schemas']['SalaryTemplateItemInput'][];
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    UpdateSalaryProfileRequest: {
      name?: string;
      employerName?: string | null;
      payDay?: number;
      defaultSyncEntry?: boolean;
      defaultItems?: components['schemas']['SalaryTemplateItemInput'][];
    };
    SalaryTemplateItemInput: {
      /** @enum {string} */
      itemType: 'EARNING' | 'DEDUCTION';
      itemCode: string;
      itemName: string;
      amountCent: components['schemas']['NonNegativeCent'];
      sortOrder: number;
    };
    SalaryRecordItemInput: {
      /** @enum {string} */
      itemType: 'EARNING' | 'DEDUCTION';
      itemCode: string;
      itemName: string;
      amountCent: components['schemas']['Cent'];
      sortOrder: number;
    };
    CreateSalaryRecordRequest: {
      /** Format: uuid */
      profileId: string;
      salaryMonth: string;
      items?: components['schemas']['SalaryRecordItemInput'][];
      /** @default false */
      copyPreviousMonth: boolean;
      idempotencyKey: components['schemas']['IdempotencyKey'];
    } & (
      | {
          /** @constant */
          copyPreviousMonth?: false;
        }
      | {
          /** @constant */
          copyPreviousMonth: true;
        }
    );
    UpdateSalaryRecordRequest: {
      items: components['schemas']['SalaryRecordItemInput'][];
    };
    MarkSalaryPaidRequest: {
      paidDate: components['schemas']['BusinessDate'];
      syncEntry: boolean;
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    CreateSavingGoalRequest: {
      /** Format: uuid */
      ledgerId: string;
      name: string;
      targetCent: components['schemas']['Cent'];
      initialCent: components['schemas']['NonNegativeCent'];
      targetDate?: components['schemas']['BusinessDate'] | null;
      /** Format: uri */
      coverUrl?: string | null;
      note?: string | null;
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    UpdateSavingGoalRequest: {
      name?: string;
      targetCent?: components['schemas']['Cent'];
      targetDate?: components['schemas']['BusinessDate'] | null;
      /** Format: uri */
      coverUrl?: string | null;
      note?: string | null;
    };
    CreateSavingContributionRequest: {
      amountCent: components['schemas']['Cent'];
      businessDate: components['schemas']['BusinessDate'];
      note?: string | null;
      idempotencyKey: components['schemas']['IdempotencyKey'];
    };
    UpdateSavingContributionRequest: {
      amountCent?: components['schemas']['Cent'];
      businessDate?: components['schemas']['BusinessDate'];
      note?: string | null;
    };
    MarkNotificationsReadRequest: {
      ids: string[];
    };
  };
  responses: {
    /** @description 查询或更新成功 */
    ResourceOk: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ResourceResponse'];
      };
    };
    /** @description 创建成功 */
    ResourceCreated: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ResourceResponse'];
      };
    };
    /** @description 邀请创建成功；明文凭证只在本响应中返回 */
    InvitationCreated: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['InvitationCreatedResponse'];
      };
    };
    /** @description 分页查询成功 */
    ResourceListOk: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ResourceListResponse'];
      };
    };
    /** @description 分类列表与服务端权限能力查询成功 */
    CategoryListOk: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['CategoryListResponse'];
      };
    };
    /** @description 账目查询或更新成功 */
    EntryOk: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['EntryResponse'];
      };
    };
    /** @description 手工账目创建或幂等重放成功 */
    EntryCreated: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['EntryResponse'];
      };
    };
    /** @description 账目分页查询成功 */
    EntryListOk: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['EntryListResponse'];
      };
    };
    /** @description 账目首次软删除或经完整校验后的幂等重试成功 */
    EntryDeleted: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['EntryDeleteResponse'];
      };
    };
    /** @description 操作成功 */
    ActionOk: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ActionResponse'];
      };
    };
    /** @description 本人工资档案查询或更新成功 */
    SalaryProfileOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SalaryProfileResponse'];
      };
    };
    /** @description 本人工资档案创建或幂等重放成功 */
    SalaryProfileCreated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SalaryProfileResponse'];
      };
    };
    /** @description 本人工资档案列表查询成功 */
    SalaryProfileListOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SalaryProfileListResponse'];
      };
    };
    /** @description 本人工资记录查询或更新成功 */
    SalaryRecordOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SalaryRecordResponse'];
      };
    };
    /** @description 本人工资记录创建或幂等重放成功 */
    SalaryRecordCreated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SalaryRecordResponse'];
      };
    };
    /** @description 本人工资记录分页查询成功 */
    SalaryRecordListOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SalaryRecordListResponse'];
      };
    };
    /** @description 认证成功并通过 HttpOnly Cookie 设置轮换用 Refresh Token */
    AuthTokenOk: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        'Set-Cookie'?: string;
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['AuthTokenResponse'];
      };
    };
    /** @description 账本月度统计概览查询成功 */
    StatisticsOverviewOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['StatisticsOverviewResponse'];
      };
    };
    /** @description 账本完整逐日收支趋势查询成功 */
    StatisticsTrendOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['StatisticsTrendResponse'];
      };
    };
    /** @description 账本支出分类统计查询成功 */
    StatisticsCategoriesOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['StatisticsCategoriesResponse'];
      };
    };
    /** @description 账本成员支出统计查询成功 */
    StatisticsMembersOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['StatisticsMembersResponse'];
      };
    };
    /** @description 本人年度工资汇总查询成功 */
    SalaryAnnualSummaryOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SalaryAnnualSummaryResponse'];
      };
    };
    /** @description 本人工资周期余额查询成功 */
    SalaryBalanceOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SalaryBalanceResponse'];
      };
    };
    /** @description 当前用户可见的攒钱目标分页查询成功 */
    SavingGoalListOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SavingGoalListResponse'];
      };
    };
    /** @description 攒钱目标创建或幂等重放成功 */
    SavingGoalCreated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SavingGoalResponse'];
      };
    };
    /** @description 攒钱目标详情查询或更新成功 */
    SavingGoalDetailOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SavingGoalDetailResponse'];
      };
    };
    /** @description 存入记录创建或幂等重放成功 */
    SavingContributionCreated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SavingContributionResponse'];
      };
    };
    /** @description 本人存入记录更新成功 */
    SavingContributionOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SavingContributionResponse'];
      };
    };
    /** @description 目标或本人存入记录软删除成功 */
    SavingDeleteOk: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['SavingDeleteResponse'];
      };
    };
    /** @description CSV 文件 */
    CsvExport: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        'Content-Disposition'?: string;
        [name: string]: unknown;
      };
      content: {
        'text/csv': string;
      };
    };
    /** @description 请求参数不合法 */
    ValidationFailed: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description 未认证或会话已失效 */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description 无权执行目标操作 */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description 资源不存在或按安全策略不可见 */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description 幂等、唯一性、并发或业务状态冲突 */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
    /** @description 请求过于频繁 */
    RateLimited: {
      headers: {
        'Retry-After'?: number;
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorResponse'];
      };
    };
  };
  parameters: {
    Id: string;
    GoalId: string;
    LedgerId: string;
    LedgerIdOptional: string;
    /** @description 缺省为用户时区当前月 */
    StatisticsMonth: string;
    Page: number;
    PageSize: number;
    Year: number;
  };
  requestBodies: never;
  headers: {
    /** @description 当前请求追踪标识 */
    RequestId: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  registerWithEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      201: components['responses']['AuthTokenOk'];
      400: components['responses']['ValidationFailed'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  loginWithPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      200: components['responses']['AuthTokenOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      429: components['responses']['RateLimited'];
    };
  };
  authorizeQq: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 跳转至 QQ OAuth */
      302: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      429: components['responses']['RateLimited'];
    };
  };
  handleQqCallback: {
    parameters: {
      query: {
        code: string;
        state: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 登录完成后跳转至手机端 */
      302: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['ValidationFailed'];
      429: components['responses']['RateLimited'];
    };
  };
  refreshAccessToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['AuthTokenOk'];
      401: components['responses']['Unauthorized'];
      429: components['responses']['RateLimited'];
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ActionOk'];
      429: components['responses']['RateLimited'];
    };
  };
  requestPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgotPasswordRequest'];
      };
    };
    responses: {
      200: components['responses']['ActionOk'];
      400: components['responses']['ValidationFailed'];
      429: components['responses']['RateLimited'];
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest'];
      };
    };
    responses: {
      200: components['responses']['ActionOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      200: components['responses']['AuthTokenOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
    };
  };
  checkAdminAccess: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ActionOk'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      401: components['responses']['Unauthorized'];
    };
  };
  updateCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest'];
      };
    };
    responses: {
      200: components['responses']['ResourceOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
    };
  };
  listLedgers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceListOk'];
      401: components['responses']['Unauthorized'];
    };
  };
  getLedger: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  createCoupleLedger: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCoupleLedgerRequest'];
      };
    };
    responses: {
      201: components['responses']['ResourceCreated'];
      400: components['responses']['ValidationFailed'];
      409: components['responses']['Conflict'];
    };
  };
  dissolveCoupleLedger: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ActionOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  updateCoupleLedger: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCoupleLedgerRequest'];
      };
    };
    responses: {
      200: components['responses']['ResourceOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  createCoupleInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCoupleInvitationRequest'];
      };
    };
    responses: {
      201: components['responses']['InvitationCreated'];
      403: components['responses']['Forbidden'];
      409: components['responses']['Conflict'];
    };
  };
  acceptCoupleInvitation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AcceptInvitationRequest'];
      };
    };
    responses: {
      200: components['responses']['ResourceOk'];
      400: components['responses']['ValidationFailed'];
      409: components['responses']['Conflict'];
    };
  };
  leaveCoupleLedger: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ActionOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  transferCoupleLedgerOwnership: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferCoupleOwnershipRequest'];
      };
    };
    responses: {
      200: components['responses']['ResourceOk'];
      400: components['responses']['ValidationFailed'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
    };
  };
  listCategories: {
    parameters: {
      query: {
        ledgerId: components['parameters']['LedgerId'];
        type?: components['schemas']['EntryType'];
        includeDisabled?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['CategoryListOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  createCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCategoryRequest'];
      };
    };
    responses: {
      201: components['responses']['ResourceCreated'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  reorderCategories: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderCategoriesRequest'];
      };
    };
    responses: {
      200: components['responses']['CategoryListOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  updateCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCategoryRequest'];
      };
    };
    responses: {
      200: components['responses']['ResourceOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  enableCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  disableCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      429: components['responses']['RateLimited'];
    };
  };
  listEntries: {
    parameters: {
      query: {
        ledgerId: components['parameters']['LedgerId'];
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
        month?: string;
        type?: components['schemas']['EntryType'];
        categoryId?: string;
        creatorUserId?: string;
        keyword?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['EntryListOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  createEntry: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateEntryRequest'];
      };
    };
    responses: {
      201: components['responses']['EntryCreated'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  getEntry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['EntryOk'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  deleteEntry: {
    parameters: {
      query: {
        expectedVersion: number;
      };
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['EntryDeleted'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  updateEntry: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateEntryRequest'];
      };
    };
    responses: {
      200: components['responses']['EntryOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  listDebts: {
    parameters: {
      query?: {
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceListOk'];
      401: components['responses']['Unauthorized'];
    };
  };
  createDebt: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDebtRequest'];
      };
    };
    responses: {
      201: components['responses']['ResourceCreated'];
      400: components['responses']['ValidationFailed'];
    };
  };
  getDebt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      404: components['responses']['NotFound'];
    };
  };
  deleteDebt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ActionOk'];
      404: components['responses']['NotFound'];
    };
  };
  updateDebt: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateDebtRequest'];
      };
    };
    responses: {
      200: components['responses']['ResourceOk'];
      404: components['responses']['NotFound'];
    };
  };
  createDebtTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDebtTransactionRequest'];
      };
    };
    responses: {
      201: components['responses']['ResourceCreated'];
      400: components['responses']['ValidationFailed'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
    };
  };
  listRecurringRules: {
    parameters: {
      query?: {
        ledgerId?: components['parameters']['LedgerIdOptional'];
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceListOk'];
      401: components['responses']['Unauthorized'];
    };
  };
  createRecurringRule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRecurringRuleRequest'];
      };
    };
    responses: {
      201: components['responses']['ResourceCreated'];
      400: components['responses']['ValidationFailed'];
      403: components['responses']['Forbidden'];
      409: components['responses']['Conflict'];
    };
  };
  getRecurringRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      404: components['responses']['NotFound'];
    };
  };
  deleteRecurringRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ActionOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  updateRecurringRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRecurringRuleRequest'];
      };
    };
    responses: {
      200: components['responses']['ResourceOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  pauseRecurringRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      409: components['responses']['Conflict'];
    };
  };
  resumeRecurringRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      409: components['responses']['Conflict'];
    };
  };
  listRecurringRuns: {
    parameters: {
      query?: {
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
        status?: components['schemas']['RecurringRunStatus'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceListOk'];
      401: components['responses']['Unauthorized'];
    };
  };
  confirmRecurringRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmRecurringRunRequest'];
      };
    };
    responses: {
      200: components['responses']['SalaryRecordOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  skipRecurringRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceOk'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
    };
  };
  listSalaryProfiles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SalaryProfileListOk'];
      401: components['responses']['Unauthorized'];
    };
  };
  createSalaryProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSalaryProfileRequest'];
      };
    };
    responses: {
      201: components['responses']['SalaryProfileCreated'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  updateSalaryProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSalaryProfileRequest'];
      };
    };
    responses: {
      200: components['responses']['SalaryProfileOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      429: components['responses']['RateLimited'];
    };
  };
  listSalaryRecords: {
    parameters: {
      query?: {
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
        year?: number;
        profileId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SalaryRecordListOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
    };
  };
  createSalaryRecord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSalaryRecordRequest'];
      };
    };
    responses: {
      201: components['responses']['SalaryRecordCreated'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  getSalaryRecord: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SalaryRecordOk'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  updateSalaryRecord: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSalaryRecordRequest'];
      };
    };
    responses: {
      200: components['responses']['SalaryRecordOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
      429: components['responses']['RateLimited'];
    };
  };
  markSalaryPaid: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MarkSalaryPaidRequest'];
      };
    };
    responses: {
      200: components['responses']['ResourceOk'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
    };
  };
  getSalarySummary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        year: components['parameters']['Year'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SalaryAnnualSummaryOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
    };
  };
  getSalaryBalance: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SalaryBalanceOk'];
      401: components['responses']['Unauthorized'];
    };
  };
  listSavingGoals: {
    parameters: {
      query?: {
        ledgerId?: components['parameters']['LedgerIdOptional'];
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SavingGoalListOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
    };
  };
  createSavingGoal: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSavingGoalRequest'];
      };
    };
    responses: {
      201: components['responses']['SavingGoalCreated'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
    };
  };
  getSavingGoal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SavingGoalDetailOk'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  deleteSavingGoal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SavingDeleteOk'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  updateSavingGoal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSavingGoalRequest'];
      };
    };
    responses: {
      200: components['responses']['SavingGoalDetailOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  addSavingContribution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSavingContributionRequest'];
      };
    };
    responses: {
      201: components['responses']['SavingContributionCreated'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      409: components['responses']['Conflict'];
    };
  };
  deleteSavingContribution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goalId: components['parameters']['GoalId'];
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['SavingDeleteOk'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  updateSavingContribution: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        goalId: components['parameters']['GoalId'];
        id: components['parameters']['Id'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateSavingContributionRequest'];
      };
    };
    responses: {
      200: components['responses']['SavingContributionOk'];
      400: components['responses']['ValidationFailed'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  getStatisticsOverview: {
    parameters: {
      query: {
        ledgerId: components['parameters']['LedgerId'];
        /** @description 缺省为用户时区当前月 */
        month?: components['parameters']['StatisticsMonth'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['StatisticsOverviewOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  getStatisticsTrend: {
    parameters: {
      query: {
        ledgerId: components['parameters']['LedgerId'];
        /** @description 缺省为用户时区当前月 */
        month?: components['parameters']['StatisticsMonth'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['StatisticsTrendOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  getStatisticsCategories: {
    parameters: {
      query: {
        ledgerId: components['parameters']['LedgerId'];
        /** @description 缺省为用户时区当前月 */
        month?: components['parameters']['StatisticsMonth'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['StatisticsCategoriesOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  getStatisticsMembers: {
    parameters: {
      query: {
        ledgerId: components['parameters']['LedgerId'];
        /** @description 缺省为用户时区当前月 */
        month?: components['parameters']['StatisticsMonth'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['StatisticsMembersOk'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  listNotifications: {
    parameters: {
      query?: {
        page?: components['parameters']['Page'];
        pageSize?: components['parameters']['PageSize'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['ResourceListOk'];
      401: components['responses']['Unauthorized'];
    };
  };
  markNotificationsRead: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MarkNotificationsReadRequest'];
      };
    };
    responses: {
      200: components['responses']['ActionOk'];
      400: components['responses']['ValidationFailed'];
    };
  };
  exportEntriesCsv: {
    parameters: {
      query: {
        ledgerId: components['parameters']['LedgerId'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['CsvExport'];
      403: components['responses']['Forbidden'];
      429: components['responses']['RateLimited'];
    };
  };
  exportSalaryCsv: {
    parameters: {
      query?: {
        year?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components['responses']['CsvExport'];
      429: components['responses']['RateLimited'];
    };
  };
}
