packages:
  - apps/*
  - packages/*

overrides:
  '@hono/node-server': '2.0.11'
  brace-expansion: '5.0.9'
  fast-uri: '3.1.4'
  js-yaml: '4.3.0'
  postcss: '8.5.23'
  valibot: '1.4.2'

patchedDependencies:
  minimatch@3.1.5: patches/minimatch@3.1.5.patch
  minimatch@5.1.9: patches/minimatch@5.1.9.patch
  minimatch@9.0.9: patches/minimatch@9.0.9.patch

allowBuilds:
  '@prisma/engines': true
  argon2: true
  core-js: false
  esbuild: true
  msgpackr-extract: false
  prisma: true
